FROM python:3.10-slim


WORKDIR /workspace


ENV PYTHONUNBUFFERED=1


COPY requirements.txt dashboards/requirements.txt /workspace/
RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 8501


CMD ["streamlit", "run", "dashboards/wrapped_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
